

---
- !ruby/object:Elibri::ONIX::Dict::Release_3_0::ProductAvailabilityType
  onix_code: '20'
  const_name: AVAILABLE
  name:
    en: available
    pl: dostępny

- !ruby/object:Elibri::ONIX::Dict::Release_3_0::ProductAvailabilityType
  onix_code: '21'
  const_name: IN_STOCK
  name:
    en: in stock
    pl: na stanie
- !ruby/object:Elibri::ONIX::Dict::Release_3_0::ProductAvailabilityType
  onix_code: '40'
  const_name: NOT_AVAILABLE
  name:
    en: not available
    pl: niedostępne
- !ruby/object:Elibri::ONIX::Dict::Release_3_0::ProductAvailabilityType
  onix_code: '10'
  const_name: NOT_YET_AVAILABLE
  name:
    en: not yet available
    pl: jeszcze niedostępne
- !ruby/object:Elibri::ONIX::Dict::Release_3_0::ProductAvailabilityType
  onix_code: '99'
  const_name: CONTACT_SUPPLIER
  name:
    en: Contact supplier
    pl: skontaktuj się z dostawcą

